model = "gpt-5.4"
[projects."~"]
trust_level = "untrusted"

[projects."~/Documents/test"]
trust_level = "trusted"

[projects."~/dotfiles"]
trust_level = "trusted"

[projects."/Users/tristan/dotfiles"]
trust_level = "trusted"

[projects."/Users/tristan/Documents/puzzle"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"
