# prefix
set -g prefix C-b
unbind C-a
bind C-b send-prefix

# terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# vi mode
setw -g mode-keys vi

# mouse
set -g mouse on

# index from 0
set -g base-index 0
setw -g pane-base-index 0

# fast escape
set -sg escape-time 0

# reload
bind r source-file ~/.tmux.conf \; display "Reloaded"

# splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# status bar
set -g status-style "bg=default,fg=white"
