# ─────────────────────────────────────────────
# kitty.conf — dwarf fortress dedicated
# ─────────────────────────────────────────────

# ── window ──────────────────────────────────
background_opacity         0.7
background_blur            40
hide_window_decorations    yes
window_padding_width       0
confirm_os_window_close    0

# ── GitHub Dark Default — color scheme ──────
foreground                 #f0f6f6
background                 #000000

# normal colors
color0                     #0d1117
color1                     #ff7b72
color2                     #3fb950
color3                     #d29922
color4                     #58a6ff
color5                     #bc8cff
color6                     #39c5cf
color7                     #b1bac4

# bright colors
color8                     #6e7681
color9                     #ffa198
color10                    #56d364
color11                    #e3b341
color12                    #79c0ff
color13                    #d2a8ff
color14                    #56d4dd
color15                    #f0f6fc

# ── misc ────────────────────────────────────
enable_audio_bell          no
shell_integration          disabled
